# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('made_from', models.CharField(default='Good product', max_length=400)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=1)),
                ('added_on', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quality', models.CharField(choices=[('G', 'Good'), ('B', 'Bad'), ('E', 'Excellent')], max_length=1)),
            ],
        ),
    ]
