# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='made_from',
            field=models.CharField(max_length=400),
        ),
    ]
