# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20160808_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media/img-thing.jpg', upload_to='/media'),
        ),
    ]
