# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media/img-thing.jpg', upload_to='/media/'),
        ),
    ]
