# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_remove_brand_category_items'),
        ('items', '0010_auto_20160814_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
        ),
    ]
