# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_auto_20160808_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stars', models.IntegerField()),
                ('season_discount', models.IntegerField()),
                ('category_items', models.ManyToManyField(to='items.Item')),
            ],
        ),
    ]
