# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category_items',
        ),
    ]
